Buling local storage for users
Caren-Koroeny/carensiya-portfolio pull request #12
Opened 2022-12-23 16:07 UTC by Caren-Koroeny

- When the user changes the content of any input field, the data is saved to the local storage.
- When the user loads the page, if there is any data in the local storage the input fields are pre-filled with this data.

2022-12-23 20:16 UTC, huseyinbiyik commented
Hi @Caren-Koroeny,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

You have submitted a project, that has no contribution from your pair programming partner. Kindly check the [Work and Submission Mode](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/10_localstorage.md#work-and-submission-mode) to learn more.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-23 20:29 UTC, Caren-Koroeny commented
- So sorry about this we are working on it asap.Thank you so much for that.

2022-12-23 21:22 UTC, huseyinbiyik requested changes
Hi @Caren-Koroeny and @shaaibu7 ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Good Readme file 👨‍💼
- Linter checks passes 🟢


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-23 21:22 UTC, huseyinbiyik commented on index.html
>              <div class="contact-form" >
Great job team! But please make sure that your contact form is working on the desktop version. Contact form input areas are not clickable right now. Kindly check the gif below.
![Screen Recording 2022-12-24 at 12 13 46 AM](https://user-images.githubusercontent.com/25887253/209406359-b3726332-c8d6-4c82-91e4-153c888d4dff.gif)

2022-12-24 00:30 UTC, binhussen approved these changes
Hi @Caren-Koroeny , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-24 01:45 UTC, merged