Making Accessibility changes
Caren-Koroeny/carensiya-portfolio pull request #6
Opened 2022-12-13 11:05 UTC by Caren-Koroeny

- `Page title` - No issues found
- no

2022-12-13 13:41 UTC, mrprotocoll commented on css/desktop-styling.css
> +    color: #6070FF;
Changed colors to fulfill color contrast accessibility

2022-12-13 14:22 UTC, Caren-Koroeny commented on index.html
>          </ul>
-  Changes for interaction accessibility.

2022-12-13 14:23 UTC, Caren-Koroeny commented on index.html
> +              <li><a href="#"> <i class="fa-solid fa-hand-peace"></i></a></li>
- Changes for interaction accessibility

2022-12-14 03:50 UTC, mrprotocoll commented on index.html
> +                <label for="subject" class="form-label">Subject:</label>
Add form labels and hide them to match the Figma design

2022-12-14 04:20 UTC, mrprotocoll commented on index.html
>                  <textarea class="text-area" id="subject" name="subject" placeholder="Write your message here"  maxlength="500" required ></textarea>
Fixed interaction accessibility, Added form labels, and hide them to match the Figma design

2022-12-14 04:21 UTC, mrprotocoll commented on index.html
> +        <h2 class="project-title">Tonic</h2>
fix heading issues

2022-12-14 04:27 UTC, mrprotocoll commented on index.html
> +          <h2 class="project-title desktop">Multi-Post Stories</h2>
fix heading issues

2022-12-14 04:28 UTC, mrprotocoll commented on index.html
> +        <h2 class="project-title desktop">Uber Navigation</h2>
fix heading issues

2022-12-14 04:29 UTC, mrprotocoll commented on index.html
> +        </h2>
fix title heading issue

2022-12-14 08:44 UTC, Olamarx requested changes
Hi @Caren-Koroeny,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

## Highlights
- Linters passed ✔️ 
- Tab accessibility ✔️ 

## Required Changes ♻️
_Check the comments under the review._
- [ ] Kindly make your title adequately descriptive such as Mark's portfolio.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 08:44 UTC, Olamarx commented on index.html
> +      <img src="./images/image-1.png" alt="Image" class="image">
- [ ] Kindly make your alt descriptive and it does not need to include the words "button", "link", or "image of". (Screen readers automatically provide that information.). Kindly apply this to others too.

2022-12-14 08:44 UTC, Olamarx commented on index.html
>          <div class="intro-text">
- [ ] The content in this tag moves and lasts more than five seconds and it is infinite. In cases like this, the best practice is that there should be a way the user can stop it so that they can have control over it but if you did not add that, I would implore you to set a time out for it.

2022-12-14 11:26 UTC, mrprotocoll commented on index.html
>          <div class="intro-text">
Alright, Thank you @Olamarx. we will make the changes

2022-12-14 11:45 UTC, Yazino12 approved these changes
## Hi @Caren-Koroeny  and @mrprotocoll 🖐🏾,

You guys have done an amazing job adding the changes requested by the previous reviewer 👍🏽, there is nothing else left to say other than it's time to merge it 🚀🚀.

### To Highlight:
- Well-documented PR ✔
- Good communication with the reviewer ✔

# STATUS: APPROVED ✅✅✅
![DANCE](https://camo.githubusercontent.com/51746859d842dcf7cf581bfd25e8426ce89edbb4b0105080e43e2379340bcfd4/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f324e704b674275555a745870752f67697068792e676966)
_Check the comments under the review 👇🏽👇🏽👇🏽._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏 💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @Yazino12 when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 12:07 UTC, merged